name: tsf
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=25.0
  - python=3.10.0
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - axial-positional-embedding==0.3.12
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - colt5-attention==0.11.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.5.0
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - docopt==0.6.2
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - fsspec==2024.10.0
      - huggingface-hub==0.30.2
      - hyper-connections==0.1.15
      - idna==3.10
      - ipdb==0.13.13
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - local-attention==1.11.1
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mpmath==1.3.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.8.0.87
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - packaging==25.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.0.0
      - pipreqs==0.5.0
      - platformdirs==4.3.8
      - product-key-memory==0.2.11
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-triton==3.3.0+git96316ce5
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - reformer-pytorch==1.4.4
      - requests==2.32.3
      - rpds-py==0.25.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - six==1.17.0
      - sklearn==0.0.post12
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch==2.8.0.dev20250422+cu128
      - torchaudio==2.6.0.dev20250422+cu128
      - torchinfo==1.8.0
      - torchvision==0.22.0.dev20250422+cu128
      - tornado==6.5
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - xxhash==3.5.0
      - yarg==0.1.9
      - yarl==1.20.0
      - torchsort==0.1.10