Neurolib:
  enc_in: 2000
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Solar:
  enc_in: 5162
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Atec:
  enc_in: 1569
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Meter:
  enc_in: 2898
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Temp:
  enc_in: 3774
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Wind:
  enc_in: 3696
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Traffic-CA:
  enc_in: 7491
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Traffic-GLA:
  enc_in: 3376
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Traffic-GBA:
  enc_in: 2229
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Air Quality:
  enc_in: 1105
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

SIRS:
  enc_in: 2994
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

SP500:
  enc_in: 1475
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

M5:
  enc_in: 3049
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Measles:
  enc_in: 1161
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Wiki-20k:
  enc_in: 112333
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Mobility:
  enc_in: 5826
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Rebound:
  enc_in: 6000
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Wiki-2k:
  enc_in: 2000
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5

Wiki-20k:
  enc_in: 20000
  train_epochs: 10
  d_ff: 64
  n_cluster: 10
  individual: c
  learning_rate: 0.001
  beta: 0.5
