Neurolib:
  enc_in: 2000
  train_epochs: 10
  d_model: 512
  d_ff: 512
  e_layers: 2

Solar:
  enc_in: 5162
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Atec:
  enc_in: 1569
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Meter:
  enc_in: 2898
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Temp:
  enc_in: 3774
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Wind:
  enc_in: 3696
  train_epochs: 10
  d_model: 256
  d_ff: 512
  e_layers: 2
  n_heads: 2

Traffic-CA:
  enc_in: 7491
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Traffic-GLA:
  enc_in: 3376
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Traffic-GBA:
  enc_in: 2229
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Air Quality:
  enc_in: 1105
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

SIRS:
  enc_in: 2994
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

SP500:
  enc_in: 1475
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

M5:
  enc_in: 3049
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Measles:
  enc_in: 1161
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Wiki:
  enc_in: 112333
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Mobility:
  enc_in: 5826
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Rebound:
  enc_in: 6000
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Wiki-2k:
  enc_in: 2000
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2

Wiki-20k:
  enc_in: 20000
  train_epochs: 10
  d_model: 64
  d_ff: 64
  e_layers: 2
  n_heads: 2
